version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    tty: true
    stdin_open: true
    restart: unless-stopped

  gui:
    build: ./gui
    volumes:
      - ./gui:/app
    ports:
      - '8080:8080'
    depends_on:
      - redis
      - server
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  redis_data:
